import React from 'react';
import './MapContainer.css';

const MapContainer = ({ geemapHtml, showDangerZones }) => {
  return (
    <div className="map-container">
      {/* 
        The geemap HTML is injected here. 
        WARNING: Using dangerouslySetInnerHTML can be risky if the source is not trusted.
        Here, we trust the HTML generated by our own geemap/FastAPI backend.
      */}
      <div
        className="geemap-render-target"
        dangerouslySetInnerHTML={{ __html: geemapHtml }}
      />

      {/* Pulsing danger zone overlay */}
      {showDangerZones && (
        <div className="danger-zone-overlay">
          <div className="pulsing-zone"></div>
        </div>
      )}

      <div className="map-labels">
          <div className="embassy-label">Embassy Alpha</div>
      </div>
    </div>
  );
};

export default MapContainer;